### ISSUE TITLE
Output performance of Numbers

### ISSUE THREAD

**Issue by stevebleazard** [dbuenzli/jsonm#11]
When converting numbers to strings string_of_float has a significant performance impact when the number is an INT. Detecting INTs and using string_of_int significantly improves performance.  Thus, using
```ocaml
let f2s f = 
  (* Check value is in the JSON integer range, maybe not necessary *)
  if f > 9007199254740991. || f < -9007199254740991. then string_of_float f 
  else
    let i = int_of_float f in
    let f1 = float_of_int i in
    if f1 = f then string_of_int i 
    else string_of_float f 
```
Has a cost of around 6.5% for floats but results in around 4x performance improvement for INTs. Here are comparisons of straight `string_of_float` and `f2s` for 1,000,000 conversions:

string_of_float
```
1,552,011,783      cycles
2,958,207,469      instructions
```
f2s
```
  363,014,703      cycles                   
  945,099,124      instructions
```
Is it worth integrating this into the encoder?

**Comment by dbuenzli** [comment]
Why not. I see you filed an issue upstream though ([MPR7724](https://caml.inria.fr/mantis/view.php?id=7724)). 

Note that one caveat of your `f2s` function in general is that it relies on unspecified behaviour (`nan`s on `int_of_float`). However in `jsonm`'s case serializing  `nan`s is [forbidden](http://erratique.ch/software/jsonm/doc/Jsonm.html#2_Encode) anyways.

**Comment by dbuenzli** [comment]
[`jsont`](https://erratique.ch/software/jsont) having been released, `jsonm` is in maintenance mode and will not be developed further. I suggest you focus your efforts on `jsont` if you are still interested.
