### ISSUE TITLE
Consider escaping U+2028 and U+2029

### ISSUE THREAD

**Issue by favonia** [dbuenzli/jsonm#15]
Unescaped U+2028 (line separator) and U+2029 (paragraph separator) are allowed in JSON strings but not in JavaScript strings. Therefore, technically speaking, JSON is not a subset of JavaScript. It is a bug in the standards IMO, and perhaps we could ease the pain by escaping these two characters so that `jsonm` only outputs valid JavaScript.

~The fix is simple---only the `must_escape` function needs to be changed.~ EDIT: I might have misread the code so let me remove this part.

**Comment by dbuenzli** [comment]
Jsonm assumes the input you give it is UTF-8 valid, this allows to avoid decoding the input to rencode it right away and makes it easy to perform the [mandatory escapes](https://tools.ietf.org/html/rfc7159#section-7) as there are all in the US-ASCII subset and easy to detect at the byte level. 

The aim of Jsonm is to not to generate JavaScript, it's to generate valid JSON. I suggest you post-process your outputs if that's a problem for you.

**Comment by favonia** [comment]
Makes sense. Thanks. I started this PR only because my initial reading thought `must_escape` is getting a Unicode code point.

The good news is that ES2019 fixed the problem on the JavaScript side and so this will be a non-issue after all the implementations get updated.
