### ISSUE TITLE
1.0.1 fails with ocaml-4.12: Error: Unbound module Uutf

### ISSUE THREAD

**Issue by yurivict** [dbuenzli/jsonm#18]
```
File "src/jsonm.ml", line 41, characters 25-35:
41 | let u_rep = Uchar.to_int Uutf.u_rep
                              ^^^^^^^^^^
Error: Unbound module Uutf
Command exited with code 2.
```

I have ocaml-uutf-1.0.2 installed.

OS: FreeBSD 13

**Comment by dbuenzli** [comment]
I'm afraid it will be difficult to help with so little details, but even if you have uutf installed it doesn't seem to be found. I don't know what you are doing but you should rather use https://opam.ocaml.org/ to install OCaml software.

**Comment by yurivict** [comment]
> I don't know what you are doing but you should rather use https://opam.ocaml.org/ to install OCaml software.

I work on the FreeBSD port so opam is out of question.

Need to build it from source.

I run:
> ocamlbuild src/jsonm.cmxs src/jsonm.cma src/jsonm.a

**Comment by yurivict** [comment]
Are there build instructions? Can dune be used?

**Comment by dbuenzli** [comment]
Try to add `-use-ocamfind` to the invocation but in general I would suggest to use  the [build instructions](https://github.com/dbuenzli/jsonm/blob/master/README.md#installation) which are in the readme.

**Comment by yurivict** [comment]
```ocamlbuild src/jsonm.cmxs src/jsonm.cma src/jsonm.a -use-ocamfind``` fails.

Also the above link doesn't have build instructions.

**Comment by dbuenzli** [comment]
It's `-use-ocamlfind` (I wrote it  initially wrong but edited) the response. 

> Also the above link doesn't have build instructions.

Yes it does if you read: 

> If you don't use opam consult the opam file for build instructions.

With a direct link to the `opam` file in which it shouldn't be too hard to spot the build invocation there.
