### ISSUE TITLE
Error: This expression has type Stdlib.Uchar.t but an expression was expected of type Uchar/1.t

### ISSUE THREAD

**Issue by yurivict** [dbuenzli/jsonm#19]
```
===>  Building for ocaml-jsonm-1.0.1.7
cd /disk-samsung/ports-ocaml/converters/ocaml-jsonm/work/jsonm-1.0.1-7-g7220492 && ocamlbuild -use-ocamlfind src/jsonm.cmxs src/jsonm.cma src/jsonm.a
+ ocamlfind ocamlopt -c -bin-annot -safe-string -package uutf -I src -I test -o src/jsonm.cmx src/jsonm.ml
File "src/jsonm.ml", line 40, characters 25-35:
40 | let u_rep = Uchar.to_int Uutf.u_rep
                              ^^^^^^^^^^
Error: This expression has type Stdlib.Uchar.t
       but an expression was expected of type Uchar/1.t
       File "_none_", line 1:
         Definition of module Uchar/1
Command exited with code 2.
```

Version: 1.0.1-7-g7220492
ocaml-uutf-1.0.2
ocaml-4.12
OS: FreeBSD 13

**Comment by dbuenzli** [comment]
Everything builds fine here with 4.12 and uutf-1.0.2 via `"ocaml" "pkg/pkg.ml" "build"`. 

I don't know exactly how your system package manager installs stuff but I suspect there may be some kind of bad interaction with `uchar` compatibility package. 

Maybe try to find some help on https://discuss.ocaml.org or better simply use opam, the repository of package is tested extensively and everything thing should work out of the box.
