### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kit-ty-kate** [dbuenzli/jsonm#21]
Hi, would it be possible to have a new release of jsonm? The last release was (exactly! Nice coincidence :D) 6 years ago and https://github.com/dbuenzli/jsonm/commit/0248232eba3daef58d2692727e476c56af0622f1 makes `master` quite attractive, especially for us opam developers as we could drop the only remaining ad-hoc patch we have: https://github.com/ocaml/opam/blob/1762a4efb8cdf25985ed875c8261494f63264f5d/src_ext/patches/jsonm.pkg/0001-remove-uchar-dep.patch

**Comment by dbuenzli** [comment]
> (exactly! Nice coincidence :D)

This totally convinced me on doing that asap. https://github.com/ocaml/opam-repository/pull/23469
